relativitydev/relativity.testing.framework.api

README.md, docs/dev/architecture.md, source/Relativity.Testing.Framework.Api.Documentation/articles/Common-use-cases-and-examples.md, source/Relativity.Testing.Framework.Api.Documentation/articles/Getting-Started.md, source/Relativity.Testing.Framework.Api.Documentation/articles/Using-Custom-Strategies.md, source/Relativity.Testing.Framework.Api.Documentation/articles/Using-Field-Service.md, source/Relativity.Testing.Framework.Api.Documentation/articles/Using-ObjectManagerService.md, source/Relativity.Testing.Framework.Api.Documentation/articles/Using-version-range-attribute.md, source/Relativity.Testing.Framework.Api.Documentation/articles/What-is-Relativity-Testing-Framework-Api.md, source/Relativity.Testing.Framework.Api.Documentation/index.md, source/Relativity.Testing.Framework.Api/Services/IAgentService.cs
=> [TESTENG-1457] Updating documentation references to the public URI.

source/Relativity.Testing.Framework.Api.Documentation/docfx.json
=> Testeng 1562 add cross repo links

.github/workflows/ReleaseBranch.yaml, source/Relativity.Testing.Framework.Api.Documentation/Relativity.Testing.Framework.Api.Documentation.csproj
=> TESTENG-1562: Update docfx to 2.58.4

CODE_OF_CONDUCT.md
=> TESTENG-1565: Add Code of Conduct

source/Relativity.Testing.Framework.Api/Services/ILibraryApplicationService.cs
=> RTF-1288 - Add examples for ILibraryApplicationService

source/Relativity.Testing.Framework.Api/Services/IScriptService.cs
=> RTF-1301 - Add examples for IScriptService

source/Relativity.Testing.Framework.Api/Services/IProductionPlaceholderService.cs
=> RTF-1296 - Add examples for IProductionPlaceholderService

source/Relativity.Testing.Framework.Api/Services/IResourceServerService.cs
=> RTF-1299 - Add examples for IResourceServerService

source/Relativity.Testing.Framework.Api/Services/IProductionService.cs
=> [RTF-1297] Adding examples to IProductionService docs.

source/Relativity.Testing.Framework.Api/Services/IProductionDataSourceService.cs, source/Relativity.Testing.Framework.Api/Services/ISearchProviderService.cs
=> RTF-1295 - Add examples for IProductionDataSourceService

source/Relativity.Testing.Framework.Api/Services/IResourcePoolService.cs
=> [RTF-1298] Adding examples to IResourcePoolService docs.

source/Relativity.Testing.Framework.Api/Strategies/Users/UserDeleteByIdStrategyPreOsier.cs, source/Relativity.Testing.Framework.Api/Strategies/Users/UserDeleteByIdStrategyV1.cs
=> RTF-1397 - Add delete User V1 strategy

source/Relativity.Testing.Framework.Api.FunctionalTests/Strategies/Users/UserGetGroupsStrategyFixture.cs, source/Relativity.Testing.Framework.Api.Tests/Extensions/UserDtoV1ExtensionsFixture.cs, source/Relativity.Testing.Framework.Api/Extensions/UserDtoV1Extensions.cs, source/Relativity.Testing.Framework.Api/Services/IUserService.cs, source/Relativity.Testing.Framework.Api/Services/UserService.cs, source/Relativity.Testing.Framework.Api/Strategies/Clients/ClientGetByIdStrategyV1.cs, source/Relativity.Testing.Framework.Api/Strategies/Users/Dto/DocumentViewerPropertiesDtoV1.cs, source/Relativity.Testing.Framework.Api/Strategies/Users/Dto/UserDtoV1.cs, source/Relativity.Testing.Framework.Api/Strategies/Users/IUserGetGroupsStrategy.cs, source/Relativity.Testing.Framework.Api/Strategies/Users/UserGetByIdStrategyPreOsier.cs, source/Relativity.Testing.Framework.Api/Strategies/Users/UserGetByIdStrategyV1.cs, source/Relativity.Testing.Framework.Api/Strategies/Users/UserGetGroupsStrategy.cs
=> RTF-1397 - Create new version of Get User strategy

source/Relativity.Testing.Framework.Api/Strategies/Users/UserCreateStrategy.cs, source/Relativity.Testing.Framework.Api/Strategies/Users/UserCreateStrategyPreOsier.cs, source/Relativity.Testing.Framework.Api/Strategies/Users/UserCreateStrategyV1.cs, source/Relativity.Testing.Framework.Api/Strategies/Users/UserUpdateStrategy.cs, source/Relativity.Testing.Framework.Api/Strategies/Users/UserUpdateStrategyPreOsier.cs, source/Relativity.Testing.Framework.Api/Strategies/Users/UserUpdateStrategyV1.cs
=> RTF-1397 - Create new versions of Create and Update User strategies

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_enhancement.yml
=> Removing syntactical formatting from issue titles, also adding 'untriaged' to the default labels generated on new issues.

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_enhancement.yml
=> Adding some default title text for the issue templates.

source/Relativity.Testing.Framework.Api/Services/IItemPermissionService.cs
=> RTF-1285 - Add examples for IItemPermissionService

source/Relativity.Testing.Framework.Api.FunctionalTests/Strategies/Folder/FolderQueryStrategyFixture.cs, source/Relativity.Testing.Framework.Api.Tests/Strategies/Folder/FolderQueryStrategyFixture.cs, source/Relativity.Testing.Framework.Api/Services/FolderService.cs, source/Relativity.Testing.Framework.Api/Services/IFolderService.cs, source/Relativity.Testing.Framework.Api/Strategies/Folder/DTO/FolderQueryRequest.cs, source/Relativity.Testing.Framework.Api/Strategies/Folder/FolderQueryStrategy.cs, source/Relativity.Testing.Framework.Api/Strategies/Folder/IFolderQueryStrategy.cs
=> [TESTENG-1575] Adding Query strategy for FolderService.

source/Relativity.Testing.Framework.Api.FunctionalTests/Strategies/Folder/FolderDeleteUnusedStrategyFixture.cs, source/Relativity.Testing.Framework.Api.Tests/Strategies/Folder/FolderDeleteUnusedStrategyFixture.cs, source/Relativity.Testing.Framework.Api/Services/FolderService.cs, source/Relativity.Testing.Framework.Api/Services/IFolderService.cs, source/Relativity.Testing.Framework.Api/Strategies/Folder/FolderDeleteUnusedStrategy.cs, source/Relativity.Testing.Framework.Api/Strategies/Folder/IFolderDeleteUnusedStrategy.cs
=> [TESTENG-1574] Adding DeleteUnused strategy for FolderService.

source/Relativity.Testing.Framework.Api.FunctionalTests/Strategies/Layouts/LayoutDeleteByIdStrategyFixture.cs, source/Relativity.Testing.Framework.Api.FunctionalTests/Strategies/Workspaces/WorkspaceUpdateStrategyFixture.cs, source/Relativity.Testing.Framework.Api/Services/IWorkspaceService.cs, source/Relativity.Testing.Framework.Api/Services/WorkspaceService.cs, source/Relativity.Testing.Framework.Api/Strategies/Workspaces/WorkspaceUpdateStrategyNotSupported.cs, source/Relativity.Testing.Framework.Api/Strategies/Workspaces/WorkspaceUpdateStrategyV1.cs
=> [RTF-1415] workspace strategy for Update operation

source/Relativity.Testing.Framework.Api.FunctionalTests/Strategies/Folder/FolderUpdateStrategyFixture.cs, source/Relativity.Testing.Framework.Api.Tests/Strategies/Folder/FolderUpdateStrategyFixture.cs, source/Relativity.Testing.Framework.Api/Services/FolderService.cs, source/Relativity.Testing.Framework.Api/Services/IFolderService.cs, source/Relativity.Testing.Framework.Api/Strategies/Folder/FolderUpdateStrategy.cs, source/Relativity.Testing.Framework.Api/Strategies/Folder/IFolderUpdateStrategy.cs
=> Testeng 1573

source/Relativity.Testing.Framework.Api.FunctionalTests/Strategies/Folder/FolderMoveStrategyFixture.cs, source/Relativity.Testing.Framework.Api.Tests/Strategies/Folder/FolderDtoMappingExtensionsFixture.cs, source/Relativity.Testing.Framework.Api.Tests/Strategies/Folder/FolderMoveStrategyFixture.cs, source/Relativity.Testing.Framework.Api/Services/FolderService.cs, source/Relativity.Testing.Framework.Api/Services/IFolderService.cs, source/Relativity.Testing.Framework.Api/Strategies/Folder/DTO/FolderDtoMappingExtensions.cs, source/Relativity.Testing.Framework.Api/Strategies/Folder/DTO/FolderMoveResponseDto.cs, source/Relativity.Testing.Framework.Api/Strategies/Folder/FolderMoveStrategy.cs, source/Relativity.Testing.Framework.Api/Strategies/Folder/IFolderMoveStrategy.cs
=> Testeng 1580

.github/workflows/FeatureBranch.yaml, .github/workflows/PublishTestResults.yaml, .github/workflows/ReleaseBranch.yaml, DevelopmentScripts/Invoke-FunctionalTest.ps1, Directory.Build.props
=> Testeng 1824

source/Relativity.Testing.Framework.Api.FunctionalTests/Strategies/Layouts/LayoutAddFieldsStrategyFixture.cs, source/Relativity.Testing.Framework.Api.FunctionalTests/Strategies/Layouts/LayoutCreateStrategyFixture.cs, source/Relativity.Testing.Framework.Api.FunctionalTests/Strategies/Layouts/LayoutDeleteByIdStrategyFixture.cs, source/Relativity.Testing.Framework.Api.FunctionalTests/Strategies/Layouts/LayoutGetByIdStrategyFixture.cs, source/Relativity.Testing.Framework.Api.FunctionalTests/Strategies/Layouts/LayoutGetCategoriesStrategyFixture.cs, source/Relativity.Testing.Framework.Api.FunctionalTests/Strategies/Layouts/LayoutGetEligibleOwnersStrategyFixture.cs, source/Relativity.Testing.Framework.Api.FunctionalTests/Strategies/Layouts/LayoutRequireStrategyFixture.cs, source/Relativity.Testing.Framework.Api.FunctionalTests/Strategies/Layouts/LayoutUpdateStrategyFixture.cs
=> Marking LayoutTests as ignored. They're preventing packages from being published.

.github/workflows/FeatureBranch.yaml, .github/workflows/PublishTestResults.yaml, .github/workflows/ReleaseBranch.yaml, source/Relativity.Testing.Framework.Api/ApiComponent.cs
=> Testeng 1865 add tiger lily tests and update sundrop

.github/workflows/FeatureBranch.yaml, .github/workflows/ReleaseBranch.yaml
Build running w/o error ( w/ code on featurebranch.yaml for evidence): https://github.com/relativitydev/relativity.testing.framework.api/actions/runs/1608411239
Record in NR: https://onenr.io/0DvwBg9AVRp
=> TESTENG-1872: Add SendBuildEvent for posting data to RelEye

.github/workflows/ReleaseBranch.yaml
=> ENGINS-1968: update build payload

catalog-info.yaml
=> ENGINS-2021: add backstage catalog info

.github/workflows/ReleaseBranch.yaml
=> ENGINS-2021: refactor to use SendBuildEvent action

.github/workflows/ReleaseBranch.yaml, CHANGELOG.md, source/Relativity.Testing.Framework.Api.Documentation/Relativity.Testing.Framework.Api.Documentation.csproj, source/Relativity.Testing.Framework.Api.FunctionalTests/Strategies/Users/UserGetGroupsStrategyFixture.cs, source/Relativity.Testing.Framework.Api/ApiComponent.cs, source/Relativity.Testing.Framework.Api/Strategies/Users/IUserGetGroupsStrategy.cs, source/Relativity.Testing.Framework.Api/Strategies/Users/UserGetGroupsStrategy.cs, source/Relativity.Testing.Framework.Api/Strategies/Users/WaitUserAddedToGroupStrategy.cs, source/Relativity.Testing.Framework.Api/Strategies/Users/WaitUserRemoveFromGroupStrategy.cs
=> Fix adding a user to a group when the user is a member of 100+ groups

catalog-info.yaml
=> DEVOPS-176822: Updated owner in catalog-info.yaml

README.md
=> DEVOPS-177053: updated readme.md with Dev Env contacts

source/Relativity.Testing.Framework.Api.FunctionalTests/Strategies/Imaging/Job/ImagingJobSubmitMassDocumentStrategyFixture.cs
=> PSD-25892-test-patch: Disabled test preventing releases

.github/workflows/ReleaseBranch.yaml
=> REL-912383: Added Push Artifactory step to workflow yaml

.github/workflows/ReleaseBranch.yaml
=> PSD-107420: Fix Azure login in Publish step

README.md
- N/A (no code change) If this is a user facing change, update [version.txt](https://github.com/relativitydev/relativity.testing.framework.api/blob/master/version.txt) and [CHANGELOG.md](https://github.com/relativitydev/relativity.testing.framework.api/blob/master/CHANGELOG.md)
=> Added announcement about RTF on RelOne to readme
